# frozen_string_literal: true

module RailsAiContext
  module Serializers
    # Generates CLAUDE.md optimized for Claude Code.
    # In :compact mode (default), produces ≤150 lines with MCP tool references.
    # In :full mode, delegates to MarkdownSerializer with behavioral rules.
    class ClaudeSerializer
      include TestCommandDetection
      include StackOverviewHelper
      include ToolGuideHelper
      include CompactSerializerHelper

      attr_reader :context

      def initialize(context)
        @context = context
      end

      def call
        if RailsAiContext.configuration.context_mode == :full
          FullClaudeSerializer.new(context).call
        else
          render_compact_rules
        end
      end
    end

    # Internal: full-mode Claude serializer (wraps MarkdownSerializer with behavioral rules)
    class FullClaudeSerializer < MarkdownSerializer
      include FullSerializerBehavior

      private

      def header
        <<~MD
          # #{context[:app_name]} — AI Context

          > Auto-generated by rails-ai-context v#{RailsAiContext::VERSION}
          > Generated: #{context[:generated_at]}
          > Rails #{context[:rails_version]} | Ruby #{context[:ruby_version]}

          This file gives Claude Code deep context about this Rails application's
          structure, patterns, and conventions. Use it to write idiomatic code
          that matches this project's style.
        MD
      end
    end
  end
end
