# frozen_string_literal: true

module RailsAiContext
  module Serializers
    # Shared rendering methods for compact-mode serializers (Claude, OpenCode).
    # Include in any serializer that has a `context` reader and includes
    # StackOverviewHelper, ToolGuideHelper, and TestCommandDetection.
    module CompactSerializerHelper
      private

      def render_header
        [
          "# #{context[:app_name]} — AI Context",
          "",
          "> Rails #{context[:rails_version]} | Ruby #{context[:ruby_version]}",
          "> Generated by rails-ai-context v#{RailsAiContext::VERSION}",
          ""
        ]
      end

      def render_stack_overview
        lines = [ "## Stack" ]

        schema = context[:schema]
        if schema && !schema[:error]
          lines << "- Database: #{schema[:adapter]} — #{schema[:total_tables]} tables"
        end

        models = context[:models]
        if models.is_a?(Hash) && !models[:error]
          lines << "- Models: #{models.size}"
        end

        routes = context[:routes]
        if routes && !routes[:error]
          internal = %w[action_mailbox/ active_storage/ rails/ conductor/ devise/ turbo/]
          app_ctrls = (routes[:by_controller] || {}).keys.reject { |k| internal.any? { |p| k.downcase.start_with?(p) } }
          lines << "- Routes: #{routes[:total_routes]} across #{app_ctrls.size} controllers"
        end

        jobs = context[:jobs]
        if jobs.is_a?(Hash) && !jobs[:error]
          job_count = jobs[:jobs]&.size || 0
          mailer_count = jobs[:mailers]&.size || 0
          channel_count = jobs[:channels]&.size || 0
          parts = []
          parts << "#{job_count} jobs" if job_count > 0
          parts << "#{mailer_count} mailers" if mailer_count > 0
          parts << "#{channel_count} channels" if channel_count > 0
          lines << "- Async: #{parts.join(', ')}" if parts.any?
        end

        migrations = context[:migrations]
        if migrations.is_a?(Hash) && !migrations[:error]
          pending = migrations[:pending]
          lines << "- Migrations: #{migrations[:total]} total, #{pending&.size || 0} pending"
        end

        lines.concat(full_preset_stack_lines)

        lines << ""
        lines
      end

      def render_key_models
        models = context[:models]
        return [] unless models.is_a?(Hash) && !models[:error] && models.any?

        max_show = 15
        lines = [ "## Key models (#{models.size} total)" ]
        models.keys.sort.first(max_show).each do |name|
          data = models[name]
          assoc_count = (data[:associations] || []).size
          val_count = (data[:validations] || []).size
          top_assocs = (data[:associations] || []).map { |a| "#{a[:type]} :#{a[:name]}" }.join(", ")
          line = "- **#{name}**"
          line += " (#{assoc_count}a, #{val_count}v)" if assoc_count > 0 || val_count > 0
          line += " — #{top_assocs}" if top_assocs && !top_assocs.empty?
          lines << line
          extras = model_extras_line(data)
          lines << extras if extras
        end
        lines << "- _...#{models.size - max_show} more (use `rails_get_model_details` tool)_" if models.size > max_show
        lines << ""
        lines
      end

      def render_notable_gems
        gems = context[:gems]
        return [] unless gems.is_a?(Hash) && !gems[:error]
        notable = notable_gems_list(gems)
        return [] if notable.empty?

        lines = [ "## Gems" ]
        grouped = notable.group_by { |g| g[:category]&.to_s || "other" }
        grouped.each do |category, gem_list|
          names = gem_list.map { |g| g[:name] }.join(", ")
          lines << "- **#{category}**: #{names}"
        end
        lines << ""
        lines
      end

      def render_commands
        test_cmd = detect_test_command
        [
          "## Commands",
          "- `bin/dev` — start dev server",
          "- `#{test_cmd}` — run tests",
          "- `rails db:migrate` — run pending migrations",
          ""
        ]
      end

      def render_warnings
        warnings = context[:_warnings]
        return [] if warnings.nil? || warnings.empty?

        lines = [ "", "## Warnings", "" ]
        warnings.each do |w|
          lines << "- **#{w[:introspector]}** skipped: #{w[:error]}"
        end
        lines
      end

      def enforce_max_lines(lines)
        max = RailsAiContext.configuration.claude_max_lines
        if lines.size > max
          lines = lines.first(max - 2)
          lines << ""
          lines << "_Context trimmed. Use MCP tools for full details._"
        end
        lines.join("\n")
      end

      # Architecture / conventions section — moved from ClaudeSerializer so
      # Cursor (.cursorrules) and any future compact serializer can reuse.
      def render_architecture
        conv = context[:conventions]
        return [] unless conv.is_a?(Hash) && !conv[:error]

        arch = conv[:architecture] || []
        patterns = conv[:patterns] || []
        return [] if arch.empty? && patterns.empty?

        arch_labels = arch_labels_hash
        pattern_labels = pattern_labels_hash

        lines = [ "## Architecture" ]
        arch.each { |p| lines << "- #{arch_labels[p] || p}" }
        patterns.first(8).each { |p| lines << "- #{pattern_labels[p] || p}" }

        dir_struct = conv[:directory_structure] || {}

        if dir_struct["app/services"]
          services = detect_service_files
          lines << "" << "**Services:** #{services.join(', ')}" if services.any?
        end

        if dir_struct["app/jobs"]
          jobs = detect_job_files
          lines << "**Jobs:** #{jobs.join(', ')}" if jobs.any?
        end

        lines << ""
        lines
      end

      # Footer rules section — also moved from ClaudeSerializer.
      def render_footer
        test_cmd = detect_test_command
        lines = [ "## Rules" ]
        lines << "- Run `#{test_cmd}` after changes"
        lines << "- Do NOT re-read files to verify edits — trust your Edit, validate syntax only"

        conv = context[:conventions]
        if conv.is_a?(Hash) && !conv[:error]
          arch = conv[:architecture] || []
          lines << "- Follow #{arch.join(' + ')} architecture" if arch.any?
          patterns = conv[:patterns] || []
          lines << "- Use service objects for business logic" if patterns.include?("service_objects")
          lines << "- Use form objects for complex forms" if patterns.include?("form_objects")
          lines << "- Use query objects for complex queries" if patterns.include?("query_objects")
        end

        stimulus = context[:stimulus]
        if stimulus.is_a?(Hash) && !stimulus[:error] && (stimulus[:controllers]&.any? || stimulus[:total_controllers]&.positive?)
          lines << "- Stimulus controllers auto-register — no manual import in controllers/index.js needed"
        end

        before_actions = detect_before_actions
        lines << "- Global before_actions: #{before_actions.join(', ')}" if before_actions.any?

        lines << ""
        lines
      end

      # Full compact-rules pipeline. Used by ClaudeSerializer (writes to
      # CLAUDE.md) and CursorRulesSerializer (writes to .cursorrules).
      # Both files give an AI agent the same project context; only the
      # filename / distribution mechanism differs.
      def render_compact_rules
        lines = []
        lines.concat(render_header)
        lines.concat(render_stack_overview)
        lines.concat(render_key_models)
        lines.concat(render_notable_gems)
        lines.concat(render_architecture)
        lines.concat(render_commands)
        lines.concat(render_warnings)
        lines.concat(render_footer)
        lines.concat(render_tools_guide_compact)

        enforce_max_lines(lines)
      end
    end
  end
end
