# frozen_string_literal: true

module RailsAiContext
  module Serializers
    # Shared rendering methods for compact-mode serializers (Claude, OpenCode).
    # Include in any serializer that has a `context` reader and includes
    # StackOverviewHelper, DesignSystemHelper, ToolGuideHelper, and TestCommandDetection.
    module CompactSerializerHelper
      private

      def render_header
        [
          "# #{context[:app_name]} — AI Context",
          "",
          "> Rails #{context[:rails_version]} | Ruby #{context[:ruby_version]}",
          "> Generated by rails-ai-context v#{RailsAiContext::VERSION}",
          ""
        ]
      end

      def render_stack_overview
        lines = [ "## Stack" ]

        schema = context[:schema]
        if schema && !schema[:error]
          lines << "- Database: #{schema[:adapter]} — #{schema[:total_tables]} tables"
        end

        models = context[:models]
        if models.is_a?(Hash) && !models[:error]
          lines << "- Models: #{models.size}"
        end

        routes = context[:routes]
        if routes && !routes[:error]
          internal = %w[action_mailbox/ active_storage/ rails/ conductor/ devise/ turbo/]
          app_ctrls = (routes[:by_controller] || {}).keys.reject { |k| internal.any? { |p| k.downcase.start_with?(p) } }
          lines << "- Routes: #{routes[:total_routes]} across #{app_ctrls.size} controllers"
        end

        jobs = context[:jobs]
        if jobs.is_a?(Hash) && !jobs[:error]
          job_count = jobs[:jobs]&.size || 0
          mailer_count = jobs[:mailers]&.size || 0
          channel_count = jobs[:channels]&.size || 0
          parts = []
          parts << "#{job_count} jobs" if job_count > 0
          parts << "#{mailer_count} mailers" if mailer_count > 0
          parts << "#{channel_count} channels" if channel_count > 0
          lines << "- Async: #{parts.join(', ')}" if parts.any?
        end

        migrations = context[:migrations]
        if migrations.is_a?(Hash) && !migrations[:error]
          pending = migrations[:pending]
          lines << "- Migrations: #{migrations[:total]} total, #{pending&.size || 0} pending"
        end

        lines.concat(full_preset_stack_lines)

        lines << ""
        lines
      end

      def render_key_models
        models = context[:models]
        return [] unless models.is_a?(Hash) && !models[:error] && models.any?

        max_show = 15
        lines = [ "## Key models (#{models.size} total)" ]
        models.keys.sort.first(max_show).each do |name|
          data = models[name]
          assoc_count = (data[:associations] || []).size
          val_count = (data[:validations] || []).size
          top_assocs = (data[:associations] || []).map { |a| "#{a[:type]} :#{a[:name]}" }.join(", ")
          line = "- **#{name}**"
          line += " (#{assoc_count}a, #{val_count}v)" if assoc_count > 0 || val_count > 0
          line += " — #{top_assocs}" if top_assocs && !top_assocs.empty?
          lines << line
          extras = model_extras_line(data)
          lines << extras if extras
        end
        lines << "- _...#{models.size - max_show} more (use `rails_get_model_details` tool)_" if models.size > max_show
        lines << ""
        lines
      end

      def render_notable_gems
        gems = context[:gems]
        return [] unless gems.is_a?(Hash) && !gems[:error]
        notable = notable_gems_list(gems)
        return [] if notable.empty?

        lines = [ "## Gems" ]
        grouped = notable.group_by { |g| g[:category]&.to_s || "other" }
        grouped.each do |category, gem_list|
          names = gem_list.map { |g| g[:name] }.join(", ")
          lines << "- **#{category}**: #{names}"
        end
        lines << ""
        lines
      end

      def render_commands
        test_cmd = detect_test_command
        [
          "## Commands",
          "- `bin/dev` — start dev server",
          "- `#{test_cmd}` — run tests",
          "- `rails db:migrate` — run pending migrations",
          ""
        ]
      end

      def render_ui_patterns
        render_design_system(context, max_lines: 30)
      end

      def render_warnings
        warnings = context[:_warnings]
        return [] if warnings.nil? || warnings.empty?

        lines = [ "", "## Warnings", "" ]
        warnings.each do |w|
          lines << "- **#{w[:introspector]}** skipped: #{w[:error]}"
        end
        lines
      end

      def enforce_max_lines(lines)
        max = RailsAiContext.configuration.claude_max_lines
        if lines.size > max
          lines = lines.first(max - 2)
          lines << ""
          lines << "_Context trimmed. Use MCP tools for full details._"
        end
        lines.join("\n")
      end
    end
  end
end
