# frozen_string_literal: true

module RailsAiContext
  module Serializers
    # Generates per-directory AGENTS.md files for OpenCode's lazy-loading system.
    # When OpenCode's agent reads a file, it walks up the directory tree and
    # auto-loads any AGENTS.md it finds — acting as contextual split rules.
    #
    # Generated files:
    #   app/models/AGENTS.md      — model listing, loaded when editing models
    #   app/controllers/AGENTS.md — controller listing, loaded when editing controllers
    class OpencodeRulesSerializer
      attr_reader :context

      def initialize(context)
        @context = context
      end

      # @param output_dir [String] Rails root path
      # @return [Hash] { written: [paths], skipped: [paths] }
      def call(output_dir)
        written = []
        skipped = []

        files = {
          File.join("app", "models", "AGENTS.md") => render_models_reference,
          File.join("app", "controllers", "AGENTS.md") => render_controllers_reference
        }

        files.each do |relative_path, content|
          next unless content

          filepath = File.join(output_dir, relative_path)
          dir = File.dirname(filepath)
          next unless Dir.exist?(dir)

          if File.exist?(filepath) && File.read(filepath) == content
            skipped << filepath
          else
            File.write(filepath, content)
            written << filepath
          end
        end

        { written: written, skipped: skipped }
      end

      private

      def render_models_reference
        models = context[:models]
        return nil unless models.is_a?(Hash) && !models[:error] && models.any?

        lines = [
          "# ActiveRecord Models (#{models.size})",
          "",
          "> Auto-generated by rails-ai-context. Do not edit manually.",
          "> Use `rails_get_model_details` MCP tool for full details.",
          ""
        ]

        models.keys.sort.first(30).each do |name|
          data = models[name]
          assocs = (data[:associations] || []).first(3).map { |a| "#{a[:type]} :#{a[:name]}" }.join(", ")
          vals = (data[:validations] || []).size
          line = "- **#{name}**"
          line += " (table: #{data[:table_name]})" if data[:table_name]
          line += " — #{assocs}" unless assocs.empty?
          line += " [#{vals}v]" if vals > 0
          lines << line
        end

        lines << "- _...#{models.size - 30} more_" if models.size > 30
        lines << ""
        lines << "Use `rails_get_model_details(model:\"Name\")` for associations, validations, scopes, enums."

        lines.join("\n")
      end

      def render_controllers_reference
        data = context[:controllers]
        return nil unless data.is_a?(Hash) && !data[:error]
        controllers = data[:controllers] || {}
        return nil if controllers.empty?

        lines = [
          "# Controllers (#{controllers.size})",
          "",
          "> Auto-generated by rails-ai-context. Do not edit manually.",
          "> Use `rails_get_controllers` MCP tool for full details.",
          ""
        ]

        controllers.keys.sort.first(25).each do |name|
          info = controllers[name]
          actions = (info[:actions] || []).map { |a| a.is_a?(Hash) ? a[:name] : a }.compact.first(6)
          line = "- **#{name}**"
          line += " — #{actions.join(", ")}" unless actions.empty?
          lines << line
        end

        lines << "- _...#{controllers.size - 25} more_" if controllers.size > 25
        lines << ""
        lines << "Use `rails_get_controllers(controller:\"Name\")` for actions, filters, strong params."

        lines.join("\n")
      end
    end
  end
end
