# frozen_string_literal: true

module RailsAiContext
  module Serializers
    # Generates AGENTS.md optimized for OpenCode.
    # In :compact mode (default), produces ≤150 lines with MCP tool references.
    # In :full mode, delegates to MarkdownSerializer with OpenCode header.
    class OpencodeSerializer
      include TestCommandDetection
      include StackOverviewHelper
      include ToolGuideHelper
      include CompactSerializerHelper

      attr_reader :context

      def initialize(context)
        @context = context
      end

      def call
        if RailsAiContext.configuration.context_mode == :full
          FullOpencodeSerializer.new(context).call
        else
          render_compact
        end
      end

      private

      def render_compact
        lines = []
        lines.concat(render_header)
        lines.concat(render_stack_overview)
        lines.concat(render_key_models)
        lines.concat(render_notable_gems)
        lines.concat(render_architecture)
        lines.concat(render_commands)
        lines.concat(render_tools_guide_compact)
        lines.concat(render_footer)

        enforce_max_lines(lines)
      end

      def render_architecture
        conv = context[:conventions]
        return [] unless conv.is_a?(Hash) && !conv[:error]

        arch = conv[:architecture] || []
        patterns = conv[:patterns] || []
        return [] if arch.empty? && patterns.empty?

        arch_labels = arch_labels_hash
        pattern_labels = pattern_labels_hash

        lines = [ "## Architecture" ]
        arch.each { |p| lines << "- #{arch_labels[p] || p}" }
        patterns.first(8).each { |p| lines << "- #{pattern_labels[p] || p}" }
        lines << ""
        lines
      end

      def render_footer
        [
          "## Rules",
          "- Follow existing patterns and conventions",
          "- Use the MCP tools to check schema before writing migrations",
          "- Match existing code style",
          "- Run tests after changes",
          ""
        ]
      end
    end

    # Internal: full-mode OpenCode serializer (wraps MarkdownSerializer)
    class FullOpencodeSerializer < MarkdownSerializer
      include FullSerializerBehavior

      private

      def header
        <<~MD
          # #{context[:app_name]} — AI Context

          > Auto-generated by rails-ai-context v#{RailsAiContext::VERSION}
          > Generated: #{context[:generated_at]}
          > Rails #{context[:rails_version]} | Ruby #{context[:ruby_version]}

          This file gives OpenCode deep context about this Rails application's
          structure, patterns, and conventions.
        MD
      end
    end
  end
end
