# frozen_string_literal: true

module RailsAiContext
  module Serializers
    # Generates compact, imperative-tone rules for legacy .cursorrules.
    # In :compact mode (default), produces ≤200 lines pointing to MCP tools.
    # In :full mode, delegates to MarkdownSerializer with rules-style header.
    class RulesSerializer
      attr_reader :context

      def initialize(context)
        @context = context
      end

      def call
        if RailsAiContext.configuration.context_mode == :full
          FullRulesSerializer.new(context).call
        else
          render_compact
        end
      end

      private

      def render_compact
        lines = []
        lines << "# #{context[:app_name]} — Project Rules"
        lines << ""
        lines << "Rails #{context[:rails_version]} | Ruby #{context[:ruby_version]}"
        lines << ""

        # Stack overview
        schema = context[:schema]
        lines << "- Database: #{schema[:adapter]} — #{schema[:total_tables]} tables" if schema && !schema[:error]

        models = context[:models]
        lines << "- Models: #{models.size}" if models.is_a?(Hash) && !models[:error]

        routes = context[:routes]
        lines << "- Routes: #{routes[:total_routes]}" if routes && !routes[:error]

        # Gems by category
        gems = context[:gems]
        if gems.is_a?(Hash) && !gems[:error]
          notable = gems[:notable_gems] || gems[:notable] || gems[:detected] || []
          notable.group_by { |g| g[:category]&.to_s || "other" }.each do |cat, list|
            lines << "- #{cat}: #{list.map { |g| g[:name] }.join(', ')}"
          end
        end

        lines << ""

        # Key models
        if models.is_a?(Hash) && !models[:error] && models.any?
          lines << "## Models (#{models.size})"
          models.keys.sort.first(20).each do |name|
            data = models[name]
            assoc_count = (data[:associations] || []).size
            lines << "- #{name} (#{assoc_count} associations)"
          end
          lines << "- ...#{models.size - 20} more" if models.size > 20
          lines << ""
        end

        # Architecture
        conv = context[:conventions]
        if conv.is_a?(Hash) && !conv[:error]
          arch = conv[:architecture] || []
          if arch.any?
            lines << "## Architecture"
            arch.each { |p| lines << "- #{p}" }
            lines << ""
          end
        end

        # MCP tools
        lines << "## MCP tools"
        lines << "Use detail:\"summary\" first, then drill into specifics."
        lines << "- rails_get_schema — tables, columns, indexes, foreign keys"
        lines << "- rails_get_model_details — associations, validations, scopes"
        lines << "- rails_get_routes — HTTP verbs, paths, actions"
        lines << "- rails_get_controllers — actions, filters, strong params"
        lines << "- rails_get_config — cache, session, middleware"
        lines << "- rails_get_test_info — framework, factories, CI"
        lines << "- rails_get_gems — categorized gem analysis"
        lines << "- rails_get_conventions — architecture patterns"
        lines << "- rails_search_code — regex codebase search"
        lines << ""

        # Rules
        lines << "## Rules"
        lines << "- Follow existing patterns and naming conventions"
        lines << "- Use MCP tools to check schema before writing migrations"
        lines << "- Run tests after changes"
        lines << ""
        lines << "---"
        lines << "_Auto-generated by rails-ai-context. Run `rails ai:context` to regenerate._"

        lines.join("\n")
      end
    end

    # Internal: full-mode rules serializer (wraps MarkdownSerializer)
    class FullRulesSerializer < MarkdownSerializer
      private

      def header
        <<~MD
          # #{context[:app_name]} — Project Rules

          Rails #{context[:rails_version]} | Ruby #{context[:ruby_version]}
        MD
      end

      def footer
        <<~MD
          ---
          _Auto-generated by rails-ai-context. Run `rails ai:context` to regenerate._
        MD
      end
    end
  end
end
